# Generated by Django 2.2.16 on 2022-04-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220423_1247'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow_unique',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow_himself',
        ),
    ]
